### ISSUE TITLE
Latest update lead to download failure (Unable to find release)

### ISSUE THREAD

**Issue by epheterson** [cowboy/synology-update-plex#15]
This has been working great for the past week or two I've had it setup, then I noticed there was an update so pulled the new script and tested (no update at the time), seemed to work fine.

Now I have an update available, and it's failing. The browser downloads this file:
https://downloads.plex.tv/plex-media-server-new/1.19.3.2831-181d9145d/synology/PlexMediaServer-1.19.3.2831-181d9145d-x86_64.spk

The logs from update-plex:
```
Checking for a Plex Media Server update...

[ Enabling Plex Pass releases ]
Found Plex Token

[ Retrieving version data ]
Available version: 1.19.3.2831-181d9145d
Installed version: 1.19.3.2793-36efde971

New version available!

[ Finding release ]
FAIL: Unable to find release for DS415+-j/x86_64/DS415+-j

Done, with errors!
```

**Comment by cowboy** [comment]
Ok, sorry about that. I'll fix it!

**Comment by epheterson** [comment]
Thanks! I've now made a plex-update-updater so I should get the fix automagically 😃

`cd /volume1/Plex; rm -f update-plex.sh; wget "https://github.com/cowboy/synology-update-plex/releases/latest/download/update-plex.sh"; chmod a+x update-plex.sh; echo "Done Successfully!"`

**Comment by epheterson** [comment]
Verified that resolved it, thanks :)

**Comment by cowboy** [comment]
LOL I don't think I'd recommend auto-updating the updater. I'm not likely to add anything that will make a difference in how plex is auto-updated on your NAS, except maybe to break it with a bug 😉
