### ISSUE TITLE
Failing to update Plex Media Server

### ISSUE THREAD

**Issue by greenthomasd** [cowboy/synology-update-plex#22]
### Script output
bash /volume1/Software/Scripts/update-plex.sh --plex-pass

Add update-plex.sh script output here.
Checking for a Plex Media Server update...

[ Initializing notification system ]
Notifications installed

[ Enabling Plex Pass releases ]
Found Plex Token

[ Retrieving version data ]
Available version: 1.19.5.3035-864bbcbb7
Installed version: 1.19.4.2935-79e214ead

New version available!

[ Finding release ]
{
  "label": "Intel 64-bit (DSM 6.0 and newer)",
  "build": "linux-x86_64",
  "distro": "synology",
  "url": "https://downloads.plex.tv/plex-media-server-new/1.19.5.3035-864bbcbb7/synology/PlexMediaServer-1.19.5.3035-864bbcbb7-x86_64.spk",
  "checksum": "8947a3d4bdd9f68d003860df0e0b197b7c1163a4"
}

[ Downloading release package ]
2020-07-20 08:19:00 URL:https://downloads.plex.tv/plex-media-server-new/1.19.5.3035-864bbcbb7/synology/PlexMediaServer-1.19.5.3035-864bbcbb7-x86_64.spk [109557760/109557760] -> "/tmp/plex.jaN1WN/PlexMediaServer-1.19.5.3035-864bbcbb7-x86_64.spk" [1]

[ Verifying checksum ]
Checksum valid!

[ Installing package ]
Failed to install package /tmp/plex.jaN1WN/PlexMediaServer-1.19.5.3035-864bbcbb7-x86_64.spk, error = [289]

[ Cleaning up ]
Removing /tmp/plex.jaN1WN

Done, with errors!

### NAS Model
DS916+

### DSM Version
DSM 6.2.3-25426 

### Additional context
The script was working like a champ for over a month, and then stopped working unexpectedly.

**Comment by cowboy** [comment]
I did a google search for "synopkg install error 289" and found the following answers in https://forums.plex.tv/t/script-to-auto-update-plex-on-synology-nas-rev6/479748/6:

> Hey guys I fixed the 289 error when installing.
> 
> Package Center -> Settings -> Trust Level -> Any publisher

and 

> I tried your script and get:
> Failed to install package /tmp/PlexMediaServer-1.18.9.2571-e106a8a91-x86_64.spk, error = [289]
> 
> Any suggestion?
> 
> Edit: Fixed: Changing the trust level in package center to any publisher fixed that error.

**Comment by cowboy** [comment]
I had already addressed this in the readme, but I'll make it more clear. Tell me if these instructions help:

https://support.plex.tv/hc/en-us/articles/205165858

**Comment by greenthomasd** [comment]
Hmmm, this is interesting. I previously added that Plex as a trusted source, but it is no longer there. I wonder if a DSM update reset this? Not for you to worry about. 

Thank you for the help. The common issues section is also more clear now, so that you for that also. How can I sent you some money for this? 

You can close this issue!

**Comment by cowboy** [comment]
There's a donation button in the readme, thanks!

[![Donate](https://img.shields.io/badge/Support%20this%20project!-$5-success)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=RRUNYDUYBAH58&source=url)

**Comment by greenthomasd** [comment]
Donated! Thanks again. It is amazing what happens when you read. :)
