### ISSUE TITLE
Error with auto update

### ISSUE THREAD

**Issue by gurvancodying** [cowboy/synology-update-plex#23]
Hi, i just installed your script and thanks for your great job by i have an error with it :

Tâche : Auto Update Plex
Heure de début : Thu, 21 Jan 2021 17:45:52 GMT
Heure d’arrêt : Thu, 21 Jan 2021 17:47:02 GMT
État actuel : 1 (Interrompu)
Sortie standard/erreur :
Checking for a Plex Media Server update...

[ Retrieving version data ]
Available version: 1.21.1.3876-3c3adfcb4
Installed version: 1.18.5.2309-f5213a238

New version available!

[ Finding release ]
{
  "label": "Intel 64-bit (DSM 6.0 and newer)",
  "build": "linux-x86_64",
  "distro": "synology",
  "url": "https://downloads.plex.tv/plex-media-server-new/1.21.1.3876-3c3adfcb4/synology/PlexMediaServer-1.21.1.3876-3c3adfcb4-x86_64.spk",
  "checksum": "c7d9f94ccc001bb5b4a0c1a47bf829dff52a08aa"
}

[ Downloading release package ]
2021-01-21 17:46:59
URL:https://downloads.plex.tv/plex-media-server-new/1.21.1.3876-3c3adfcb4/synology/PlexMediaServer-1.21.1.3876-3c3adfcb4-x86_64.spk
[111687680/111687680] ->
"/tmp/plex.3rVtU8/PlexMediaServer-1.21.1.3876-3c3adfcb4-x86_64.spk"
[1]

[ Verifying checksum ]
Checksum valid!

[ Installing package ]
Failed to install package
/tmp/plex.3rVtU8/PlexMediaServer-1.21.1.3876-3c3adfcb4-x86_64.spk,
error = [288]

[ Cleaning up ]
Removing /tmp/plex.3rVtU8

Done, with errors!

Thanks a lot for your help

**Comment by cowboy** [comment]
Can you try with this version of the script and post its output here?

https://raw.githubusercontent.com/cowboy/synology-update-plex/3f4821ab9179dc8e4b9188c24cf2b18e166c733a/update-plex.sh

Also, what's your NAS model and DSM version?

**Comment by gurvancodying** [comment]
Ok i just tried, and this is the output : 

[ Retrieving version data ]
Available version: 1.21.1.3876-3c3adfcb4
Installed version: 1.18.5.2309-f5213a238

New version available!

[ Finding release ]
{
  "label": "Intel 64-bit (DSM 6.0 and newer)",
  "build": "linux-x86_64",
  "distro": "synology",
  "url": "https://downloads.plex.tv/plex-media-server-new/1.21.1.3876-3c3adfcb4/synology/PlexMediaServer-1.21.1.3876-3c3adfcb4-x86_64.spk",
  "checksum": "c7d9f94ccc001bb5b4a0c1a47bf829dff52a08aa"
}

[ Downloading release package ]
2021-01-21 18:45:09
URL:https://downloads.plex.tv/plex-media-server-new/1.21.1.3876-3c3adfcb4/synology/PlexMediaServer-1.21.1.3876-3c3adfcb4-x86_64.spk
[111687680/111687680] ->
"/tmp/plex.czLLoE/PlexMediaServer-1.21.1.3876-3c3adfcb4-x86_64.spk"
[1]

[ Verifying checksum ]
Checksum valid!

[ Installing package ]
Failed to install package
/tmp/plex.czLLoE/PlexMediaServer-1.21.1.3876-3c3adfcb4-x86_64.spk,
error = [288]

[ Cleaning up ]
Removing /tmp/plex.czLLoE

[ Debugging info ]
script_args=()
script_version='(in-development)'
available_version=1.21.1.3876-3c3adfcb4
installed_version=1.18.5.2309-f5213a238
tmp_dir=/tmp/plex.czLLoE
package_file=/tmp/plex.czLLoE/PlexMediaServer-1.21.1.3876-3c3adfcb4-x86_64.spk

Done, with errors!

**Comment by cowboy** [comment]
What's your NAS model and DSM version?

Also, can you tell me the output of the following commands?

* `uname -m`
* `cat /proc/sys/kernel/syno_hw_version`

**Comment by gurvancodying** [comment]
Of course :
uname -m
x86_64
cat /proc/sys/kernel/syno_hw_version
DS218+

**Comment by sphynx630** [comment]
I figured this out. It fails at install and gave me a [289] error which has to do with the Plex certificate in Package Center. @gurvancodying try following the steps found here: [https://support.plex.tv/articles/205165858-how-to-add-plex-s-package-signing-public-key-to-synology-nas-package-center/?_ga=2.162387836.1194402430.1571755454-1617362326.1543598076](url) and then running the script.

**Comment by gurvancodying** [comment]
> I figured this out. It fails at install and gave me a [289] error which has to do with the Plex certificate in Package Center. @gurvancodying try following the steps found here: [https://support.plex.tv/articles/205165858-how-to-add-plex-s-package-signing-public-key-to-synology-nas-package-center/?_ga=2.162387836.1194402430.1571755454-1617362326.1543598076](url) and then running the script.

I already installed the certificate and my error is not a 289 but a 288

**Comment by sphynx630** [comment]
I did too but when I went to check it was not there. Can you confirm the certificate still shows up in package center?

**Comment by gurvancodying** [comment]
just checked and the certificate was not there...
Reinstalled it and now it's ok, i don't understand why it disapeared

**Comment by cowboy** [comment]
I there a known list of errors for `synopkg install`? I'd love to get some better error messages into the script.

**Comment by cowboy** [comment]
> Reinstalled it and now it's ok, i don't understand why it disapeared

Is the problem solved? Or still occurring?

**Comment by gurvancodying** [comment]
for the moment it's ok, i reload my syno and the certificate is there. For me all is ok, thanks for your time

**Comment by MajorLOL** [comment]
Close the issue please.

**Comment by bolshukhin** [comment]
Hello. Is it compatible with DSM 7? Tnx
