### ISSUE TITLE
Done, with error 289

### ISSUE THREAD

**Issue by mak-cs** [cowboy/synology-update-plex#27]
### Script output
```
Aufgabe: Plex Server Update
Startzeit: Thu, 08 Apr 2021 11:52:11 GMT
Stoppzeit: Thu, 08 Apr 2021 11:52:28 GMT
Aktueller Status: 1 (Unterbrochen)
Standardausgabe/Fehler:
Checking for a Plex Media Server update...

[ Retrieving version data ]
Available version: 1.22.2.4282-a97b03fad
Installed version: 1.22.1.4275-6000

New version available!

[ Finding release ]
{
  "label": "Intel 64-bit (DSM 6.0 and newer)",
  "build": "linux-x86_64",
  "distro": "synology",
  "url": "https://downloads.plex.tv/plex-media-server-new/1.22.2.4282-a97b03fad/synology/PlexMediaServer-1.22.2.4282-a97b03fad-x86_64_DSM6.spk",
  "checksum": "3538303aae00573167770d018b668654406d4233"
}

[ Downloading release package ]
2021-04-08 11:52:22 URL:https://downloads.plex.tv/plex-media-server-new/1.22.2.4282-a97b03fad/synology/PlexMediaServer-1.22.2.4282-a97b03fad-x86_64_DSM6.spk [117944320/117944320] -> "/tmp/plex.ADWyUo/PlexMediaServer-1.22.2.4282-a97b03fad-x86_64_DSM6.spk" [1]

[ Verifying checksum ]
Checksum valid!

[ Installing package ]
Failed to install package /tmp/plex.ADWyUo/PlexMediaServer-1.22.2.4282-a97b03fad-x86_64_DSM6.spk, error = [289]

[ Cleaning up ]
Removing /tmp/plex.ADWyUo

Done, with errors!
```

### NAS Model
DS1517+

### DSM Version
DSM 6.2.4-25556

### Additional context
Manual installation of the same file runs successful.

**Comment by oscaritoro** [comment]
@MAK-CS : Seems like others have resolved this by either installing the Plex certificate in Package Center or changing the package trust level to "Any Publisher". If you haven't tried/verified either, I would recommend going with the "install Plex certificate in Package Center" route... Instructions can be found here: https://support.plex.tv/articles/205165858-how-to-add-plex-s-package-signing-public-key-to-synology-nas-package-center/ ...

Update: actually now that I happen to re-read @cowboy 's README.md (shown[ on main page of this project](https://github.com/cowboy/synology-update-plex)), this is actually listed as one of the common issues (3rd one)

**Comment by mak-cs** [comment]
Your link solved the problem. Tanks for supporting me.
