### ISSUE TITLE
Done, with error 288

### ISSUE THREAD

**Issue by Gruenbaer** [cowboy/synology-update-plex#29]
First I got error 289, which I resolved by installing the Plex certificate in Package Center.
After running  it again, it still fails with error 288.
uname -m
x86_64
cat /proc/sys/kernel/syno_hw_version
DS218+

Here's the output:

` Checking for a Plex Media Server update...

[ Retrieving version data ]
Available version: 1.22.2.4282-a97b03fad
Installed version: 1.22.0.4163-d8c4875dd

New version available!

[ Finding release ]
{
  "label": "Intel 64-bit (DSM 6.0 and newer)",
  "build": "linux-x86_64",
  "distro": "synology",
  "url": "https://downloads.plex.tv/plex-media-server-new/1.22.2.4282-a97b03fad/synology/PlexMediaServer-1.22.2.4282-a97b03fad-x86_64_DSM6.spk",
  "checksum": "3538303aae00573167770d018b668654406d4233"
}

[ Downloading release package ]
2021-04-18 00:35:47 URL:https://downloads.plex.tv/plex-media-server-new/1.22.2.4282-a97b03fad/synology/PlexMediaServer-1.22.2.4282-a97b03fad-x86_64_DSM6.spk [117944320/117944320] -> "/tmp/plex.pqmw2n/PlexMediaServer-1.22.2.4282-a97b03fad-x86_64_DSM6.spk" [1]

[ Verifying checksum ]
Checksum valid!

[ Installing package ]
Failed to install package /tmp/plex.pqmw2n/PlexMediaServer-1.22.2.4282-a97b03fad-x86_64_DSM6.spk, error = [288]

[ Cleaning up ]
Removing /tmp/plex.pqmw2n

[ Debugging info ]
script_args=()
script_version='(in-development)'
available_version=1.22.2.4282-a97b03fad
installed_version=1.22.0.4163-d8c4875dd
tmp_dir=/tmp/plex.pqmw2n
package_file=/tmp/plex.pqmw2n/PlexMediaServer-1.22.2.4282-a97b03fad-x86_64_DSM6.spk

Done, with errors!
`

**Comment by oscaritoro** [comment]
@Gruenbaer : would you be able to provide the following:
1- DSM version that was running at the time you attempted the install
2- Is that DSM version still running? 
3- Are you still seeing this same issue above?
4- Are you running as root?
5- If you are still seeing this issue, could you grab the last few/relevant lines of /var/log/messages for synopkg (maybe use `tail -100 /var/log/messages |grep synopkg` immediately after)?
6- If you are still seeing this issue, could you grab the last few/relevant lines of /var/log/synopgk.log (maybe use `tail -50 /var/log/synopkg.log` immediately after)?

**Comment by Gruenbaer** [comment]
Hello,
thanks to your questions and looking at the logs I figured it out myself.
It was just my own stupidity.

The relevant entry in the /var/log/messages was:
`pkginstall.cpp:166 Check codesign failed`

which simply means that the plex certificate is not accepted.

The solution is simple...
Install the Plex certificate **AND** set the package center to not only allow Synology Inc. packages, but also other trusted Publishers...

Best regards,
Emil
