### ISSUE TITLE
Upgrade failing on DSM 7.0-41890

### ISSUE THREAD

**Issue by jakemauer** [cowboy/synology-update-plex#37]
### Script output
```
Checking for a Plex Media Server update...

[ Enabling Plex Pass releases ]
Found Plex Token

[ Retrieving version data ]
Available version: 1.24.0.4930-ab6e1a058

Done, with errors!
```

### NAS Model
DS1019+

### DSM Version
DSM 7.0-41890

### Additional context
Updated to the latest version of the script and re-ran a few times before posting the issue. Plex's install/upgrade seemed to go well and it's functioning normally otherwise.

EDIT: I should also add I was using the script successfully on DSM 6 and I am running it as root. Also, thank you for your work on this script, it's saved me a ton of time on tedious upgrades!

**Comment by steffen-klein** [comment]
### Script output

```
sudo sh ./update-plex.sh --plex-pass
Checking for a Plex Media Server update...

[ Enabling Plex Pass releases ]
Found Plex Token

[ Retrieving version data ]
Available version: 1.24.0.4930-ab6e1a058

Done, with errors!
```

### NAS Model

DS918+

### DSM Version

DSM 7.0-41890

### Additional context

I have the same issue. When starting the script in the terminal, I get the same error message.
When I run the script via DSM 7.0 Task Scheduler, I get the following Event message (addresses removed):

```
{"%COMPANY_NAME%":"Synology DiskStation","%DATE%":"2021-08-16","%DISKSTATION%":"DiskStation","%HOSTNAME%":"XXXX","%HOST_SN%":"XXX","%HTTPS_URL%":"https://XXXX/, https://XXXX/","%HTTP_URL%":"http://XXXX/, http://XXXX/","%IP_ADDR%":"192.168.0.200","%OSNAME%":"DSM","%PLEX_VERSION%":"1.24.0.4930-ab6e1a058","%TIME%":"07:50"}
```

Best,
Steffen

**Comment by jakemauer** [comment]
Wow so this turned out to be my fault. Something happened where I thought I copied over the latest script code but I hadn't, as the DSM version check function wasn't present. Updating with the actual latest code works.

**Comment by jakemauer** [comment]
I see what my issue was. I copied the code from the latest "release" but should've copied it straight from the master branch.

**Comment by steffen-klein** [comment]
Same here 😀 now it works. Thanks a lot!
