### ISSUE TITLE
Event Notification Template Output

### ISSUE THREAD

**Issue by themagicbullet** [cowboy/synology-update-plex#38]
### Problem
PR #33 added support for DSM 7. The updates are happening correctly but the event notification template is not rendering correctly. In the notifications area, I see:

```
{"%COMPANY_NAME%":"Synology DiskStation","%DATE%":"2021-08-18","%DISKSTATION%":"DiskStation","%HOSTNAME%":"[Redacted]","%HOST_SN%":"[Redacted]","%HTTPS_URL%":"[Redacted],[Redacted]","%HTTP_URL%":"[Redacted], [Redacted]","%IP_ADDR%":"[Redacted]","%OSNAME%":"DSM","%PLEX_VERSION%":"1.24.1.4931-1a38e63c6","%TIME%":"04:00"}
``` 

### NAS Model
DS218+

### DSM Version
DSM 7.0-41890

**Comment by epheterson** [comment]
I'm seeing the same, besides the formatting everything works well but would be nice to have easily-readable messages.

**Comment by cowboy** [comment]
This fix has been addressed in the latest release https://github.com/cowboy/synology-update-plex/releases
