### ISSUE TITLE
Task schedule report formatting

### ISSUE THREAD

**Issue by steffen-klein** [cowboy/synology-update-plex#41]
Hey,
I get the following message which seems to be not correctly formatted:

> Task Scheduler has completed a scheduled task.
> 
> Task: synology-update-plex
> Start time: Thu, 16 Sep 2021 04:00:01 GMT
> Stop time: Thu, 16 Sep 2021 04:06:20 GMT
> Current status: 0 (Normal)
> Standard output/error:
> Checking for a Plex Media Server update...
> 
> [ Retrieving DSM version ]
> Found DSM version 7
> 
> [ Enabling Plex Pass releases ]
> Found Plex Token
> 
> [ Retrieving version data ]
> Available version: 1.24.3.5033-757abe6b4
> Installed version: 1.24.2.5000-7000
> 
> New version available!
> 
> [ Finding release ]
> {
>  "label": "Intel 64-bit",
>  "build": "linux-x86_64",
>  "distro": "synology-dsm7",
>  "url": "https://downloads.plex.tv/plex-media-server-new/1.24.3.5033-757abe6b4/synology-dsm7/PlexMediaServer-1.24.3.5033-757abe6b4-x86_64_DSM7.spk",
>  "checksum": "b6821b741d71c897aa328d89c6bb1759961ad7d9"
> }
> 
> [ Downloading release package ]
> 2021-09-16 04:05:59 URL:https://downloads.plex.tv/plex-media-server-new/1.24.3.5033-757abe6b4/synology-dsm7/PlexMediaServer-1.24.3.5033-757abe6b4-x86_64_DSM7.spk [115445760/115445760] -> "/tmp/plex.iH8cCM/PlexMediaServer-1.24.3.5033-757abe6b4-x86_64_DSM7.spk" [2]
> 
> [ Verifying checksum ]
> Checksum valid!
> 
> [ Installing package ]
> {"error":{"code":0},"results":[{"action":"upgrade","beta":false,"betaIncoming":false,"error":{"code":0},"finished":true,"installReboot":false,"installing":true,"language":"enu","last_stage":"started","package":"PlexMediaServer","packageName":"Plex Media Server","pid":18985,"scripts":[{"code":0,"message":"","type":"stop"},{"code":0,"message":"","type":"preupgrade"},{"code":0,"message":"","type":"preuninst"},{"code":0,"message":"","type":"postuninst"},{"code":0,"message":"","type":"preinst"},{"code":0,"message":"<br><br><p style='color:blue'>Note: If Plex cannot access your media, verify user <strong>PlexMediaServer</strong> is granted permission in <strong>Control Panel</strong>.</p><br>\nSet access to your media share(s) by performing the following steps:<br><br>\n1. Open <strong>Control Panel</strong> and select <strong>Shared Folder</strong><br>\n2. Select the share which contains your media and click <strong>Edit</strong><br>\n3. Click the <strong>Permissions</strong> tab<br>\n4. 
> Change the dropdown from <strong>Local Users</strong> to <strong>System internal user</strong><br>\n5. Check the <strong>Read/Write</strong> checkbox for the <strong>PlexMediaServer</strong> user<br>\n6. Click <strong>Save</strong> to confirm the new permissions<br>\n7. Repeat steps 2-6 for each share you want Plex Media Server to access<br>\n","type":"postinst"},{"code":0,"message":"","type":"postupgrade"},{"code":0,"message":"","type":"start"}],"spk":"/tmp/plex.iH8cCM/PlexMediaServer-1.24.3.5033-757abe6b4-x86_64_DSM7.spk","stage":"installed_and_started","status":"running","success":true,"username":""}],"success":true}
> 
> [ Restarting Plex Media Server ]
> {"action":"prepare","error":{"code":0},"stage":"prepare","success":true}
> 
> [ Cleaning up ]
> Removing /tmp/plex.iH8cCM
> 
> Done!

**Comment by oscaritoro** [comment]
Looks weird because Plex got fancy in the messages they include within the returns but it's a successful update from what I can tell... the script just takes the exact returns provided and copies them into the output stream.

**Comment by ngthwi** [comment]
It's because of a debug line that should be removed at line 292:
>   echo "$release_json"

**Comment by elisimpson** [comment]
This is still an issue. Update happens but output is completely garbled. Did DSM7 change the synopkg command to output a large JSON string instead of just the success/fail message?

**Comment by cowboy** [comment]
Closed by #47

**Comment by cowboy** [comment]
This fix has been addressed in the latest release https://github.com/cowboy/synology-update-plex/releases
