### ISSUE TITLE
Script does not update anymore

### ISSUE THREAD

**Issue by AnarchyCent** [cowboy/synology-update-plex#45]
### Script output
```
Checking for a Plex Media Server update...

[ Initializing notification system ]
Notifications disabled (file /var/cache/texts/enu/mails not found)

[ Retrieving version data ]
Available version: 1.30.0.6486-629d58034

Done, with errors!

```

### NAS Model
DS918+

### DSM Version
DSM 7.1.1-42962 Update 1

### Current Plex version
1.29.0.6244

**Comment by henrysia** [comment]
You need to add Plex's certificate. Follow [these instructions](https://support.plex.tv/articles/205165858-how-to-add-plex-s-package-signing-public-key-to-synology-nas-package-center/).

**Comment by cowboy** [comment]
Seems like this was fixed, closing
