### ISSUE TITLE
need support new DSM version Synology (DSM 7.2.2+),please

### ISSUE THREAD

**Issue by listenfree** [cowboy/synology-update-plex#54]
https://plex.tv/api/downloads/5.json   
...
  "Synology (DSM 7.2.2+)": {
      "id": "synology-dsm72",
      "name": "Synology (DSM 7.2.2+)",
      "release_date": 1727090209,

**Comment by DeadMozay** [comment]
You need to replace the value in the script in the line
https://github.com/cowboy/synology-update-plex/blob/aff73c48ee99fe72242a7a87bc5607a12e22b4ff/update-plex.sh#L114 from `"Synology (DSM 7)"` to `"Synology (DSM 7.2.2+)"`

This should be enough

**Comment by Unr3aL** [comment]
See the following pull request to make it work with all versions: https://github.com/cowboy/synology-update-plex/pull/56

I took the liberty and integrated the DSM 6 fix https://github.com/cowboy/synology-update-plex/pull/53 by @bedlam-au into my pull request.

**Comment by cowboy** [comment]
Closed by #56 and released as https://github.com/cowboy/synology-update-plex/releases/tag/v1.2.0
