### ISSUE TITLE
Script is not updating Plex anymore

### ISSUE THREAD

**Issue by martinspaniol** [cowboy/synology-update-plex#57]
### Script output
```
sh-4.4$ sudo bash /volume1/homes/admin/update-plex.sh --version
v1.2.0
sh-4.4$ sudo bash /volume1/homes/admin/update-plex.sh 
Checking for a Plex Media Server update...

[ Retrieving DSM version ]
Found DSM version 7.2.2+

[ Retrieving version data ]
Available version: 1.41.2.9200-c6bbc1b53
Installed version: 1.41.2.9200-70009200

Plex is up-to-date.

Done!
```

### NAS Model
DS220+

### DSM Version
DSM 7.2.2-72806 Update 1

### Additional context
I've updated the script to the latest version. When running it reports corretly, that I've installed Plex version `1.41.2.9200-70009200` and also that version `1.41.2.9200-c6bbc1b53` is available. However, the script reports that plex is up-to-date. I'd expect the script to update Plex to the current version.

**Comment by cowboy** [comment]
It's my understanding that 1.41.2.9200-70009200 and 1.41.2.9200-c6bbc1b53 are both version 1.41.2.9200, with the characters after the version number being a checksum value that has more to do with how the artifact was built than anything else.

I'm going to close this issue, but if you can find anything that explains how those values are actually different versions of Plex, please let me know!

**Comment by martinspaniol** [comment]
@cowboy Thanks for your reply. Hm do you have an idea why package center reports that the currently installed version of plex is incompatible with my Diskstation?
![image](https://github.com/user-attachments/assets/7ef44c7f-4db6-4d12-97a5-f9236285faaa)
I thought that this might result in a older version being installed, which is why I opened this issue.

**Comment by martinspaniol** [comment]
I manually downloaded the latest version from plex directly and installed it in the package center. Then Package Center updated my already installed version and now plex is up and running.
The script still reports the same though
```
sh-4.4$ sudo /volume1/homes/admin/update-plex.sh 
Checking for a Plex Media Server update...

[ Retrieving DSM version ]
Found DSM version 7.2.2+

[ Retrieving version data ]
Available version: 1.41.2.9200-c6bbc1b53
Installed version: 1.41.2.9200-72009200

Plex is up-to-date.

Done!
```

**Comment by cowboy** [comment]
Are you saying that this script installed a version of Plex that was incompatible with your NAS? Like, the Plex that the script installed didn't work?

**Comment by martinspaniol** [comment]
Before I updated DSM from 7.2 to 7.2.2 Plex was running fine with your script. After the update to 7.2.2 package center reported that the installed version of Plex is not compatible with my DSM version. For some reason the script reported, that the latest version was already installed. I only got Plex running again by manually downloading and installing it.

**Comment by cowboy** [comment]
Ok, good to know. I'll keep my eye out for this or other related issues. Thanks!
