### ISSUE TITLE
Current version newer than latest version

### ISSUE THREAD

**Issue by maxwell-01** [cowboy/synology-update-plex#6]
Hello,
Firstly thank you for creating this script - cleaner and easier to follow than the post that led me here from plex forum.

Ran your script as is and received:

```
Checking for a Plex Media Server update...

[ Retrieving version data ]
LATEST VERSION: 1.18.9.2578-513b381af
CURRENT VERSION: 1.19.1.2589-2de7f3266
Plex is up-to-date.

Done!
```

Then switched to plexpass version (as I'm a subscriber) and got:

```
Checking for a Plex Media Server update...

[ Using plexpass release channel ]
FAIL: Unable to find Preferences.xml file

Done, with errors!
```

Please can you let me know where I'm going wrong. I installed the latest 64bit synology package from plex before trying your script.

Thanks!

**Comment by cowboy** [comment]
I just updated the script, can you download and try the newest version? Note that enabling plex pass is now done via `--plex-pass` option instead of editing the script!

If this doesn't work, I have some troubleshooting steps we can follow.

**Comment by maxwell-01** [comment]
Thanks for the quick turnaround.

Also, using an option to run against the file rather than editing it is much easier for me! I was having trouble with read-only permissions earlier. Your new update works like a charm:

root@Max-NAS:/volume1/Plex# bash update-plex.sh --plex-pass
Checking for a Plex Media Server update...

```
[ Enabling Plex Pass Releases ]
Found Plex Token

[ Retrieving version data ]
AVAILABLE VERSION: 1.19.1.2589-2de7f3266
INSTALLED VERSION: 1.19.1.2589-2de7f3266
Plex is up-to-date.

Done!
```

Thank you very much indeed :)

**Comment by maxwell-01** [comment]
On a side note - there is a feature within DSM where, for scheduled tasks, you can view the output. I noticed there was nothing in there from running this script. I don't know if its a lot of work for you, but it would be great to populate this so that I can check whats been happening.

**Comment by cowboy** [comment]
You're welcome!

And the Synology task scheduler already supports saving output results, you just have to check the box in the task scheduler settings dialog and provide a folder, like so:

![image](https://user-images.githubusercontent.com/54051/78266380-b44ba800-74d3-11ea-8ee2-a07e53179465.png)

How do I know this? Because I asked Synology support the same question a few days ago 🤦‍♂

**Comment by maxwell-01** [comment]
oh wow - thanks for putting this setting in an entirely different menu Synology!

Thanks for your help 😉
